### ISSUE TITLE
No/wrong recalculating of counter after removal of item

### ISSUE THREAD

**Issue by domaxistd** [rqrauhvmra/Tobii#100]
Hello,
it seems that the counter does not recalculate after an item is removed.

1. i add several images to the lightbox -> counter is right
2. i remove an image -> counter is wrong (shows too much items, numbers are mixed)

Is there any workaround or quick fix?

Thanks in advance!
Maxi

**Comment by midzer** [comment]
Hi @domaxistd 

first of all, thanks for opening this issue.

I have to investigate, never used the tobii counter feature myself. Looks like it's related to https://github.com/midzer/tobii/issues/93.

**Comment by domaxistd** [comment]
Thanks for the fast respond! @midzer 

Another problem that occurs is that when i remove and add multiple items, the lightbox shows too much items.
For example: 
- i have 3 items added to the lightbox
- the lightbox counter shows 8 items
- i can swipe 8 times before the lightbox closes itself even though there are only 3 items added (it loops through the 3 items)

I have already tried to reset the lightbox after i remove an item but that doesn't seem to work.

Maybe this helps you find the problem.

**Comment by domaxistd** [comment]
Any progress or findings yet?

**Comment by midzer** [comment]
@domaxistd Sorry, I was rather busy the last months. Now, over the holidays I can investigate.

**Comment by midzer** [comment]
Should be fixed by https://github.com/midzer/tobii/commit/b84f9be159d4371ca728c7f048e8c480db0409c2

Can you give it a try, @domaxistd?

**Comment by domaxistd** [comment]
@midzer problem solved, thanks!
