### ISSUE TITLE
Missing :hover and :focus styling on prev and next buttons

### ISSUE THREAD

**Issue by jakobhaerter** [rqrauhvmra/Tobii#102]
Hi there!

I was just randomly checking the color contrast of the prev and next buttons. I noticed they're set to `opacity: .5` and aren't being updated to `opacity: 1` on `:hover` or `:focus`.

Is this the intended behaviour or just a bug?

Thanks!

**Comment by viliusle** [comment]
`:focus` works, but there is no `:hover` and it would be nice to have.

**Comment by midzer** [comment]
Good point.

@jakobhaerter Wanna help out by opening a PR to development branch?
