### ISSUE TITLE
Feature Request: Zoom on mobile

### ISSUE THREAD

**Issue by Mattrushka** [rqrauhvmra/Tobii#118]
**Current behaviour**
Currently users are not able to pinch-to-zoom into Lightbox images.

**Desired behaviour**
Enable pich-to-zoom feature on mobile devices. Offer function as option setting.

**Comment by midzer** [comment]
Thanks for opening up, @Mattrushka 

Yeah, this is a good point!

**Comment by midzer** [comment]
This looks like a bigger feature, after reading through

https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events/Pinch_zoom_gestures#example

If anyone likes to work on this one, would be nice :)

**Comment by midzer** [comment]
Finally implemented via https://github.com/midzer/tobii/releases/tag/v2.6.0
