### ISSUE TITLE
tap to cycle for touchscreen devices

### ISSUE THREAD

**Issue by chri2** [rqrauhvmra/Tobii#119]
This is an duplicate from [flohmarkt](https://codeberg.org/flohmarkt/flohmarkt) where the issue has been marked as _upstream_.

application: flohmarkt
device: Librem5
browser: tangram (flatpak)

On a touchscreen devices the pictures in the gallery of an item can be changed by swiping left or right.

At least in tangram the gesture is used to navigate history back and forth which makes changing pictures in the viewer hard or impossible.

An alternative to swiping left and right could be cycling by tapping the pictures:

* `tap near the center` or `tap right side of the center`: **cycle next picture**
* `tap on the left side of center`: **cycle previous picture**

**Comment by midzer** [comment]
Done via https://github.com/midzer/tobii/releases/tag/v2.6.0
