### ISSUE TITLE
Purpose of callback functions

### ISSUE THREAD

**Issue by midzer** [rqrauhvmra/Tobii#20]
Hi,
I did not investigate when you introduced all those `callback` arguments. As all involved functions are syncronous, I wonder why we need those arguments.

So writting
```javascript
function foo () {
  // do something
}
tobi.next(foo)
```
should be the same as
```javascript
function foo () {
  // do something
}
tobi.next()
foo()
```
For my taste, those additional callback parameters just blow code up. Could you explain a possible use case for them?

Thanks in advance and have a nice day
midzer

**Comment by ghost** [comment]
Hey @midzer,

I had a few projects that should do something after a tobi action (open and close), but only if there was no error. I admit I probably overdid it with prev() and next() :-)

I think all the callbacks can be replaced with the upcoming events.
