### ISSUE TITLE
Close button and counter float on the picture

### ISSUE THREAD

**Issue by SinnerAir** [rqrauhvmra/Tobii#23]
Close button and counter float on the picture in mobile if the picture is stretched in height.

![22ea2ced31](https://user-images.githubusercontent.com/7911499/82097980-11628c80-9715-11ea-990d-1c1e1e292012.jpg)

I fixed it like this:
```
.tobii__slider {
    top: 5em;
}

[data-type] {
    height: 100%;
    max-height: 100%;
    display: flex;
    align-items: center;
}

    [data-type] > figure {
        max-height: 100%;
    } 
```

**Comment by viliusle** [comment]
Another option is to let it overlap, but adapt styles in a way, that overlaping would not be a problem.
![Screenshot 2021-06-23 at 17 23 21](https://user-images.githubusercontent.com/3708786/123114389-ee41fa80-d447-11eb-86d5-b7a2c3260400.png)

**Comment by midzer** [comment]
I'm up for both.
Let's see what others think about this... cc @ocean90

**Comment by ocean90** [comment]
I'd probably also add a safe area for the top bar and on smaller screens we may want to reduce the size of the button to 44x44px which is the recommended minimum tappable area for buttons.

Edit: The gallery at the bottom of this [article](https://www.hna.de/lokales/rotenburg-bebra/bad-hersfeld-ort56532/amazon-investiert-13-millionen-euro-am-standort-eichhof-in-bad-hersfeld-90479906.html) does something similar.

**Comment by viliusle** [comment]
![33](https://user-images.githubusercontent.com/3708786/124628078-cbbcd200-de88-11eb-9c52-0fa0a5c799ac.jpg)
Preview how it can look in small screen.

**Comment by midzer** [comment]
Looking good.
Let's see how it works out live!

**Comment by viliusle** [comment]
Another version preview:

- max height - 100%
- max-width - 100%
- top line has black color with opacity 0.5
- works well on mobile / small screen, because image can take literally 100% of screen space.

![v3](https://user-images.githubusercontent.com/3708786/127555465-14adcce6-c9fa-4d99-8b46-1a16a6719bea.jpg)

p.s. image above is not at 100%!
