### ISSUE TITLE
Any plans for Vimeo support?

### ISSUE THREAD

**Issue by marcamos** [rqrauhvmra/Tobii#24]
Hello! A quick question: are there any plans for Vimeo support in the same way YouTube is supported?

Thank you for making this – it's lovely.

**Comment by ghost** [comment]
Hey @marcamos,

support for Vimeo is on my list, but it will take some time before it will appear with the final version 2. There is still a lot to do and so little time.

**Comment by marcamos** [comment]
Thank you for the info!

**Comment by marcamos** [comment]
🎉
