### ISSUE TITLE
Thought I'd share how I stop iframe > video from playing after closing Tobii

### ISSUE THREAD

**Issue by marcamos** [rqrauhvmra/Tobii#25]
Hello,

I'm in the process of building a page where Tobii launches a Vimeo video. As Vimeo _doesn't seem to be supported_ in the same way that YouTube is, I fell back to using the `iframe` feature of Tobii, and it works well.

What I then discovered is…

1. The Vimeo video is launched in the lightbox
2. The visitor presses play
3. When the visitor wants to stop watching, they close Tobii
4. At this point, the video is _still_ playing – it's merely hidden, but it can still be heard

So, I had to determine how to _stop_ a video after the visitor clicks Tobii's close button, or its backdrop. This is what I came up with and it seems to work well:

```js
new Tobii()

const initCustomTobii = function() {
  document.querySelector('.tobii__close')?.addEventListener('click', handleTobiiIframes)
  document.querySelector('.tobii__slider')?.addEventListener('click', handleTobiiIframes)
}

const handleTobiiIframes = function() {
  const tobiiIframes = document.querySelectorAll('.tobii iframe')
  if (tobiiIframes) {
    tobiiIframes.forEach(function(iframe) {
      let src = iframe.src
      iframe.src = src
    })
  }
}

initCustomTobii()
```

I thought I'd share this in case it's helpful to others.

**Comment by viliusle** [comment]
It is fixed in latest version. Vimeo can be used with iframe now without additional coding. Check demo.
