### ISSUE TITLE
Unwanted grouping

### ISSUE THREAD

**Issue by marcamos** [rqrauhvmra/Tobii#26]
Hello! I've setup a CodePen to point out _two_ issues I'm seeing, the first of which is **unwanted grouping**.

When I have more than one lightbox element _and_ I do not use the `data-group` attribute, the lightbox behaves as if I did. See it, here:

https://codepen.io/marcamos/pen/NWxaMXQ

**Comment by ghost** [comment]
Hi @marcamos,

 which browser do you use? I can't reproduce it. In your example all three containers are shown in one lightbox.

**Comment by marcamos** [comment]
Hi @rqrauhvmra, thanks for replying. I've tried it in Firefox, Chrome, and Safari on macOS Mojave. Would you like a small screen-recording?

**Comment by ghost** [comment]
> Would you like a small screen-recording?

That would be great.

**Comment by marcamos** [comment]
In this (quick) screen-recording, I try to demonstrate two things:

1. How the lightbox items are grouped together, even though I didn't use the `data-group` attribute
2. When tabbing, the focus seems to travel to the hidden items before it gets to the visible item

[tobii.mov.zip](https://github.com/rqrauhvmra/tobii/files/4859846/tobii.mov.zip)

**Comment by ghost** [comment]
Thanks for the screen recording.

That all three elements appear in a lightbox is a normal behavior. If elements are not separated with the `data-group` attribute, all elements with the class `lightbox` are displayed in the same lightbox.

Perhaps an additional option can help to change this behavior if someone uses the lightbox to want to display each element individually.

Regarding the tabbing bug, I use the other issue.

**Comment by marcamos** [comment]
Aha, OK, thank you for the information. I thought the intended behavior was: "no grouping happens _unless explicitly asked for_ by using the `data-group` attribute."

**Comment by ghost** [comment]
I'll write the additional option to change this behavior on my list.

**Comment by marcamos** [comment]
[Thank you](https://media.giphy.com/media/QAsBwSjx9zVKoGp9nr/giphy.gif)

**Comment by mrleblanc101** [comment]
What is the option ? Can't find it

**Comment by midzer** [comment]
Does the demo https://midzer.github.io/tobii/demo/ help you @mrleblanc101?

**Comment by mrleblanc101** [comment]
Not defining a data-group currently groups everything, Instead I would want to make everything single unless I specify a data group. 

I saw this old comment https://github.com/midzer/tobii/issues/26#issuecomment-652629906 and assumed it was implemented.

I understand that this option was not added, then ? I'll add unique data-group to every single one of my instance in the meantime.

**Comment by midzer** [comment]
>  Instead I would want to make everything single unless I specify a data group.

Now I understand. We don't have this option yet.

> I'll add unique data-group to every single one of my instance in the meantime.

Yeah, that's a possible workaround.
