### ISSUE TITLE
Tabbing through hidden + grouped lightboxes

### ISSUE THREAD

**Issue by marcamos** [rqrauhvmra/Tobii#27]
Hello! I've setup a CodePen to point out _two_ issues I'm seeing, the second of which is **tabbing through hidden + grouped lightboxes**.

When a handful of grouped `data-type="html"` lightboxes are used, the tab "flow" seems to go through _all_ of them, instead of only through the one visible lightbox. See it, here:

https://codepen.io/marcamos/pen/NWxaMXQ

**Comment by ghost** [comment]
Hi @marcamos,

I know this bug. The problem starts in issue #4. At the moment I don't know how to tab through the dynamically displayed HTML elements in the current slide (and the prev-, next- and close-buttons) without the hidden slides.

**Comment by marcamos** [comment]
Understood, thank you for the update!
