### ISSUE TITLE
Swipe-up and swiping off-image

### ISSUE THREAD

**Issue by g0vegan** [rqrauhvmra/Tobii#29]
1)  Being able to swipe up, as well as left and right, leads to the image 'jumping around', which (to me) feels and looks odd in an image gallery.  I have set "swipeClose: false" so that Tobii no longer closes on swiping up, but the image still moves up when swiped up.
--> Is it possible to disable swipe-up if 'swipeClose' is false, just as swipe-down is always disabled?

2)  When swiping left or right, if the pointer is dragged off the image, Tobii closes on mouseup, just like it would if one clicked outside the image.  I think the correct behavior would be to drag the image gallery, not close it.
--> Would it be possible to disable the "click outside image to close" functionality while dragging?

**Comment by ghost** [comment]
Hey @g0vegan,

1. Which version are you using? If `swipeClose` is `false`, the picture cannot be swiped up.
2. I will improve this point.

**Comment by g0vegan** [comment]
I am not sure exactly where to find the version, but this is copied from package.json:

  "version": "2.0.0-alpha",
  "description": "An accessible, open-source lightbox with no dependencies.",
  "main": "dist/js/tobii.js",
  "style": "dist/css/tobii.css",
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "@babel/preset-env": "^7.8.6",
    "@rollup/plugin-commonjs": "^11.0.2",
    "@rollup/plugin-node-resolve": "^7.1.1",
    "autoprefixer": "^9.7.4",
    "rollup": "^1.32.0",
    "rollup-plugin-babel": "^4.3.3",
    "rollup-plugin-babel-minify": "^9.1.1",
    "standard": "^14.3.1"
  }

This is my configuration:

var tobii = new Tobii({
  zoom: false,
  swipeClose: false,
  threshold: 5
});

Images can be swiped left, right, or up but not down.  When swiped up, they come back down and nothing else happens.

**Comment by ghost** [comment]
Thank you for your answer @g0vegan. Which browser do you use?

**Comment by g0vegan** [comment]
I have tested on several browsers and it happens on all of them, the latest versions of:

Firefox
Chrome
Edge
Brave

The same thing happens on every one...

The only possibly unusual thing that I am doing is that I block the default click event as follows using CSS:

a.lightbox {
  pointer-events: none;
}

... and instead use a button that performs tobii.open(photoID) when clicked.  I cannot see how that would affect "swipe up" though; everything else works perfectly.
