### ISSUE TITLE
Emit events on state changes

### ISSUE THREAD

**Issue by rqrauhvmra** [rqrauhvmra/tobii#3]

**Comment by midzer** [comment]
I think we should create and trigger events https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

This way we create hooks for `prev()`, `next()`, `open()` and `close()` functions the developer could listen to.

For one of my projects listening to `prev()` and `next()` would be very handy. I could create more lightbox elements in my media gallery dynamically https://feuerwehr-eisolzried.de/media/

As I need this feature myself, I can jump on this topic the next days.

**Comment by ghost** [comment]
Hey @midzer,

> As I need this feature myself, I can jump on this topic the next days.

That would be great. I have already experimented with `CustomEvent()` but failed because I wanted to use something like this:

```js
const tobii = new Tobii()

tobii.on('close', function() {
  // ...
})

tobii.on('select', function() {
  // ...
})
```

**Comment by midzer** [comment]
Probably it can look like
```javascript
tobii.addEventListener('close', function() {
  // ...
})
```

**Comment by danielpost** [comment]
I believe it would be trivial to add the `on` wrapper as well, using something like this (untested):

```js
const on = (event, callback) => {
  tobii.addEventListener(event, callback());
}
```

It wouldn't add much benefit other than a shorter syntax though.

**Comment by ghost** [comment]
For explanation: The idea behind `on()` was to provide `off()` and `once()` in the future too.
