### ISSUE TITLE
Question: PreventDefault in touchmove event

### ISSUE THREAD

**Issue by SinnerAir** [rqrauhvmra/Tobii#31]
The code contains such a line  https://github.com/rqrauhvmra/tobii/blob/ac432322c09dc30eba853a17b252250ba87ed453/src/js/tobii.js#L1234
Can you find out what it is for? Because it does not provide the ability to scale with a gesture.

**Comment by midzer** [comment]
@SinnerAir Sorry for no reply the whole time. What do you mean by scale with a gesture?

> Touchmove event: triggered continuously when the finger is sliding on the screen. During this event, calling the preventdefault() event prevents scrolling.

via https://developpaper.com/implementation-of-html5-touch-events-touchstart-touchmove-and-touchend/

**Comment by viliusle** [comment]
>scale with a gesture?

scale with two fingers holding, and moving away from each other?

**Comment by viliusle** [comment]
I just tested it, removing that line does not break navigation on mobile, but allows to zoom image using 2 fingers on mobile.

**Comment by viliusle** [comment]
It should work on next version.

**Comment by midzer** [comment]
I can't get this "2-finger-zoom" zoom working on my live site (Android and Safari). Image just moves as of switch the slides.

@viliusle Can you confirm this is working? I could test in `develop` branch demo if I update the `dist` files.

**Comment by viliusle** [comment]
I tested it again with latest develop branch code on android device, chrome browser. Zoom with 2 fingers works.

p.s. I was able to zoom actual page too, but even i tap on image and modal window is activated, I still can zoom it, but I see that page itself zooms too in background. So it is not only image zoom, but zoom everything.
