### ISSUE TITLE
can be used inside js function?

### ISSUE THREAD

**Issue by franMx** [rqrauhvmra/Tobii#32]
Hi, not an issue per se, more of a question. Can tobbi be used inside a js function?

Used another library previously that allowed:

```
function pdfl(){
    var lightbox = lity('capital.html');
}
```

Is it possible to use tobii similar to that?

Thanks.

**Comment by midzer** [comment]
To be honest, I dont know exactly. Have you tried it, @franMx ?
From my programming perspective, `lightbox` instance should be in global scope, because it is running all the time. Inside a function it may be garbage collected.

**Comment by franMx** [comment]
Hi midzer, ended up using a different library, as I wasn't able to get around some issues.
