### ISSUE TITLE
Codepens are not working

### ISSUE THREAD

**Issue by babobski** [rqrauhvmra/Tobii#34]
Would love to see it in action, but getting 404's on the codepen's on you're repo.

**Comment by midzer** [comment]
Hi and thanks for your issue.

Right now, I've just replaced codepen with a live example https://github.com/midzer/tobii/commit/6ba4397d12c6ab87174cabe02a818c937b13ea67. Someday in the future I will bring back those initial codepens.

**Comment by midzer** [comment]
We have a demo page at https://midzer.github.io/tobii/demo/ (from https://github.com/midzer/tobii/tree/production/demo) now.
Feel free to extend it.

I close this one for good.
