### ISSUE TITLE
Caption spreading multiple lines

### ISSUE THREAD

**Issue by runxel** [rqrauhvmra/Tobii#36]
I need my captions to be multiple lines. Any way to achieve this?

**Comment by midzer** [comment]
@runxel Thanks for filling. Is this approach from mentioned PR good for you?

**Comment by ocean90** [comment]
The issue is probably the use of `textContent` which doesn't allow HTML and thus a `<br>` element. What might work is using a line break `\n` and setting `white-space: pre;` in CSS for the `figcaption` element.

**Comment by runxel** [comment]
Wow, very nice @ocean90! Great PR!
This was actually the next thing I wanted to have (usage of the already applied figcaption). And I certainly thought this would be a working solution, if we have this possibility, @midzer.

However, it doesn't work for me :(
I did it like the usage example in the PR, but the Firefox dev tools gave me an error:
`Uncaught TypeError: el.href is undefined`.

A better documentation for the feature would be great, too!

Maybe I misunderstood the `selector: '[data-lightbox]'` part. 
My code looks like this:
```
<a href="(...)" class="lightbox" data-group="art">
  <figure>
    <img data-lightbox src="(...)"  alt="(...) ">
    <figcaption>Test<br>New Line</figcaption>
  </figure>
</a>
```

**Comment by ocean90** [comment]
`selector` is the option to set the selector for the anchor elements. In your case you should keep the default value which is `'.lightbox'`. For `captionText` the following ES6 code should work:

```js
captionText: ( element ) => {
     const caption = element.querySelector( 'figcaption' );
     return caption ? caption.textContent : null;
},
```

As noted above, `textContent` ignores any HTML.

**Comment by runxel** [comment]
Thank you so much for your help, @ocean90!

Tobii works now, and what else I did was using `caption.innerText` instead.
Now I can have a `figcaption` like this:
```html
<figcaption>A test <br> with a new line</figcaption>
```

Nice! 💯
