### ISSUE TITLE
after closing a slide with an iframe playing sound inside, sound keep playing

### ISSUE THREAD

**Issue by eyal670** [rqrauhvmra/Tobii#37]
I'm loading a slide with a page inside iframe, the page has sound,
after closing the lightbox, the sound keep playing
I'm using this method to set the iframe slider:
```
<a href="https://www.wikipedia.org" data-type="iframe" class="lightbox">
  Open Wikipedia
</a>

<script>
jQuery( document ).ready(function() {
    const tobii = new Tobii();
});
</script>
```

**Comment by midzer** [comment]
@eyal670 Hi. Check out https://github.com/midzer/tobii/issues/25. This might be solved there.

Reopen if you still have issues.

**Comment by eyal670** [comment]
thank you
