### ISSUE TITLE
Allow caption text to be set from a callback

### ISSUE THREAD

**Issue by ocean90** [rqrauhvmra/Tobii#38]
The caption text is currently quite limited as it only supports an attribute on the element itself or the image. It would be nice to be able to use other sources for the caption text, like the content of an existing `figcaption` element.

This could be implemented by adding a new config which allows to set a custom callback. The callback would get the current element to be able to identify the correct caption and should return the relevant caption text. I'm going to submit a PR for this idea.

**Comment by midzer** [comment]
Awesome!
