### ISSUE TITLE
Doesnt work with images containing query strings

### ISSUE THREAD

**Issue by HashandSalt** [rqrauhvmra/Tobii#46]
As this title the doesnt like images containing a query string (like those coming from the Shopify CDN). This was fixed on the first version of Tobi, but doesnt seem to have been carried over to Tobii.

**Comment by midzer** [comment]
Hi @HashandSalt 
To bad I don't have access to ancient Tobi code any more.

Can you give a more detailed example what is broken now?

**Comment by HashandSalt** [comment]
If the image that is the href target for the light box has a query string on the end, the light box opens with the cross in the corner, but there is no big image in it.

A shopify image has a version on the end like `someimage.jpg?v=234234234`

**Comment by viliusle** [comment]
I believe it works fine with query strings. Maybe HashandSalt used  data-type="___something__" on image type, in this case it will not work and will give same issue as HashandSalt described.

**Comment by midzer** [comment]
@HashandSalt Can you confirm?

**Comment by midzer** [comment]
As it's apparently working we can close this one for good.

Feel free to re-open if you still have issues.
