### ISSUE TITLE
Also publish on npmjs.com

### ISSUE THREAD

**Issue by ocean90** [rqrauhvmra/Tobii#51]
@midzer I just noticed that we still have an alpha version on https://www.npmjs.com/package/tobii released. Any chance to update the version there as well?

**Comment by midzer** [comment]
@ocean90 thanks for your message.

To be honest I'm kinda stuck there. When I released v2 I ran into issues with `npm publish`. I even created an account there. Also I pushed an Action for it https://github.com/midzer/tobii/blob/production/.github/workflows/npm-publish.yml

Do you have an idea why it fails?

**Comment by ocean90** [comment]
@midzer  I think there are two issues:

* The new package name is `@midzer/tobii` which means this will be published on https://www.npmjs.com/package/@midzer/tobii. Might be good to publish a deprecation note with [npm-deprecate](https://docs.npmjs.com/cli/v7/commands/npm-deprecate) for old package name
* Jobs do not run sequentially so the change to the [npmrc](https://github.com/midzer/tobii/blob/0fe82d1edfb4a05e8654262047f19437a70ff5f7/.github/workflows/npm-publish.yml#L45) file may also be used by the npm job. This can be fixed by adding `publish-npm` to the dependencies list of `publish-gpr` so it runs after `publish-npm`.

**Comment by midzer** [comment]
@ocean90 Is this what you mean https://github.com/midzer/tobii/commit/86cf68a7a9f81f4738a447b0eaf4e7050c37ed3d

If so, I will draft a new release

**Comment by ocean90** [comment]
Yes, let's give it a try.

**Comment by midzer** [comment]
Okay, hang on a sec.

I tried to deprecate old `tobii` package. Too bad, the former maintainer did not transfer permissions to me, so I can't do it:

```
403 Forbidden - PUT https://registry.npmjs.org/tobii - You do not have permission to publish "tobii". Are you logged in as the correct user?
```

**Comment by midzer** [comment]
@ocean90 GitHub Action fails :( publish-npm runs first. Shouldn't it run second?

```
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"
```

**Comment by ocean90** [comment]
@midzer Submitted https://github.com/midzer/tobii/pull/52 which uses the official template.

**Comment by ocean90** [comment]
@midzer Uhh, the registry needs to be removed from the package.json...

https://github.com/midzer/tobii/blob/0b2127dcbb7275ccbae778374c125941955622aa/package.json#L61-L63

This overrides any npmrc setting.

**Comment by midzer** [comment]
Now, we got a new error. Thanks for helping out on this issue!

```
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@midzer%2ftobii - Forbidden
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy.
```

**Comment by ocean90** [comment]
@midzer Did you verify your email? https://stackoverflow.com/a/64718961/3507335

**Comment by midzer** [comment]
@ocean90 That was it!
Thanks for your hint. It is published now :1st_place_medal: https://www.npmjs.com/package/@midzer/tobii
