### ISSUE TITLE
No support for IE

### ISSUE THREAD

**Issue by ArturVasyliev** [rqrauhvmra/Tobii#54]
Looks like tobii doesn't work in IE (I use the latest IE for testing). I get an error in tobii.min.js and looks like it's related to arrow functions. Just wondering if there is a build that will work in IE?

**Comment by midzer** [comment]
Thanks for filing @ArturVasyliev 

Moving code base to ES6 with v2 and using microbundle (no transpile) we lost IE11 compatibility.

I am not in favor supporting an 8 year old browser in 2021. So we should update the README.

What do others think?
cc @ocean90

**Comment by ocean90** [comment]
> Moving code base to ES6 with v2 and using microbundle (no transpile) we lost IE11 compatibility.

That wasn't planned since we still include the polyfill for `CustomEvent`. This can easily be fixed by tweaking the browserslist config. @ArturVasyliev Can you give https://github.com/midzer/tobii/pull/55 a try?

**Comment by ArturVasyliev** [comment]
Sorry for the late response. Thank you @ocean90 and @midzer very much for fixing it! Tested the build in IE11 and it works great. I think we can close the issue.
