### ISSUE TITLE
Add "close" event

### ISSUE THREAD

**Issue by christopherjanzen** [rqrauhvmra/Tobii#58]
Maybe I'm missing a technique that would easily allow me to watch for this, but it would be nice to have a "close" event like the "open", "next", and "previous" that are already available.

Use case: updating a slider slide index on close to match the lightbox's last open slide.

**Comment by midzer** [comment]
@christopherjanzen Thanks for filling.

I think this just involves putting
```
// Create and dispatch a new event
const closeEvent = new window.CustomEvent('close')

lightbox.dispatchEvent(closeEvent)
```
at the end of `close()`.

Wanna contribute yourself, @christopherjanzen ?
