### ISSUE TITLE
ignore duplicates

### ISSUE THREAD

**Issue by viliusle** [rqrauhvmra/Tobii#59]
Library should ignore duplicates by default, because it makes no sense to loop through same image 3 times for example. 

Use case: having 3 tabs with same HTML code.

**Comment by midzer** [comment]
I think we could `.filter()` incoming elements Array here https://github.com/midzer/tobii/blob/72bddfb1380496e475a8407658474dedf0e38e8e/src/js/index.js#L407 and look for any duplicates.

**Comment by midzer** [comment]
@viliusle Can you double check if code works for you? I can't test properly right now...

**Comment by viliusle** [comment]
Does not work. I believe it will need more coding then few lines. Also remember, we can not just ignore duplicates, modal windows still must be called, only element should not be added into gallery items list.

p.s. it also throws JS error
