### ISSUE TITLE
inline HTML missing styles

### ISSUE THREAD

**Issue by viliusle** [rqrauhvmra/Tobii#60]
inline HTML modal dialog is missing default styles. I believe it should be included in library by default:

```
.tobii__slide div[data-type="html"]{
	background: white;
	padding: 10px 20px;
	max-width: 800px;
}
```

p.s. not related, but "Inline HTML" link on readme.md does not work.

**Comment by midzer** [comment]
@viliusle Can you show a screenshot involving those changes compared to current state?

I will happily merge this if you do a PR.

Thanks for your hint with the README. I've just fixed it https://github.com/midzer/tobii/commit/72bddfb1380496e475a8407658474dedf0e38e8e

**Comment by viliusle** [comment]
Before:
![before](https://user-images.githubusercontent.com/3708786/123990405-683b2c00-d9d2-11eb-92e6-bbf1c252f425.jpg)
After:
![after](https://user-images.githubusercontent.com/3708786/123990421-6b361c80-d9d2-11eb-80fc-11efa0206077.jpg)
