### ISSUE TITLE
animation issue

### ISSUE THREAD

**Issue by viliusle** [rqrauhvmra/Tobii#61]
Animation on second and third gallery items works only if you wait before opening second slide. If you open  gallery and try to load next and next and next item fast, there will be no animation, but it will appear for other items.

**Comment by midzer** [comment]
I can reproduce this issue.

Gonna investigate when I have more time.

**Comment by viliusle** [comment]
I believe I found it:
https://github.com/midzer/tobii/blob/production/src/js/index.js#L732

p.s. as always, fixing something with timeout will only give you troubles in future.

**Comment by midzer** [comment]
Updated relevant line: https://github.com/midzer/tobii/blob/4121463301e3241fd7e36cfa540d11c4f62a3173/src/js/index.js#L758

Would it be enough to put
```
groups[activeGroup].slider.classList.add('tobii__slider--animate')
```
just _after_ `next()` or `previous()` is called?

**Comment by viliusle** [comment]
I am thinking about remove timout and leave code in same place. I don't see any issues during testing even after changing transform duration to 5s.

**Comment by midzer** [comment]
Thanks for your effort.

Now, I will test `development` branch on one of my live sites.
