### ISSUE TITLE
Improve demo

### ISSUE THREAD

**Issue by viliusle** [rqrauhvmra/Tobii#63]
Current demo is very simple, it can give impressions that library is simple too and does not support advanced features. Also having good demo help developers with testing. i would probably include

Improvements :

- Image (single)
- Images (grouped)
- Inline HTML
- Iframe
- YouTube (not sure about it, since YouTube have to auto-play by default)
- YouTube (auto-play)
- Image with events (on-load, on-exit - _we don't have it yet_)
- Manual call on some example link/button.
- Image (not existing)
- Iframe (not existing)
- YouTube (not existing)

p.s. sorted by priority.

**Comment by midzer** [comment]
Too bad the linked examples from former maintainer are gone -> leading to 404. This is why I had them removed from README.

Right now, I am rather busy with RL. So I can't jump on this topic at the moment.

If you feel you would like to contribute, just do it :)

**Comment by viliusle** [comment]
Another issue that we have 2 demos with 99% same code. It means, adding anything in demo, you have to duplicate to another modern demo too. Remember "DRY" ...

I wish we could remove one, but we need demo for webpage, and demo during development with live code watch.
