### ISSUE TITLE
Wondering if fix for #28 will be in v2.3.0?

### ISSUE THREAD

**Issue by jdshaw** [rqrauhvmra/Tobii#84]
First of all, thanks for making this available! Its the only accessible lightbox that allows grouping of images that I've found.

My question is: Will the fix for #28 be available in v2.3.0 and is there an estimated release date for v2.3.0?

Thanks!

**Comment by viliusle** [comment]
v2.3.0 is ready, and I believe it can be released even now.

p.s. all milestones for v2.3.0 is done, except license one, which can not be done, because of other issues, and will not be done anytime soon.

@midzer we should release next feature version.

**Comment by midzer** [comment]
I am going to release the next days.

**Comment by jdshaw** [comment]
Awesome. Thanks to both of you for all of your hard work!

**Comment by midzer** [comment]
It's out now -> https://github.com/midzer/tobii/releases/tag/v2.3.0
