### ISSUE TITLE
Dragging not working

### ISSUE THREAD

**Issue by wongjn** [rqrauhvmra/Tobii#87]
In Chrome, dragging between images is not working in version `2.3.0` (was working in `2.2.0`). One can see this feature is not working by trying to drag in the *Images (grouped)* demo.

**Comment by midzer** [comment]
Thx for filling @wongjn 
I have double checked and can confirm dragging is not working any more, so we have a regression here.

**Comment by viliusle** [comment]
Dragging requires device with touch screen.

**Comment by midzer** [comment]
IIRC, dragging used to work but was a bit "clunky" on desktop. So using the next/prev buttons should be preferred.
@wongjn Can you live with that?

**Comment by wongjn** [comment]
If it still works on mobile then yes I can 😄

**Comment by midzer** [comment]
Definetely still working properly :)
I close this one for good.
