### ISSUE TITLE
Change captionText to use innerHTML instead of textContent

### ISSUE THREAD

**Issue by mbabini** [rqrauhvmra/Tobii#88]
Hi

It would be great if the output of the captionText function could contain HTML code like line breaks or links.

I suggest the following change:
original:
`this.userSettings.captionText?r.textContent=this.userSettings.captionText(e)`

new:
`this.userSettings.captionText?r.innerHTML=this.userSettings.captionText(e)`

Thank you!

**Comment by viliusle** [comment]
This can be done easily, of course needs some testing.

**Comment by midzer** [comment]
We could try it in `develop` branch.

@mbabini Do you mind opening a PR for this?

**Comment by mbabini** [comment]
@midzer I've tried: https://github.com/midzer/tobii/pull/92
But please check because it's my very first PR... ;-)

**Comment by midzer** [comment]
Should by done by https://github.com/midzer/tobii/commit/b43119e8471c8424ad32757f85a472b9d29259a4
