### ISSUE TITLE
IE11 broken

### ISSUE THREAD

**Issue by midzer** [rqrauhvmra/Tobii#91]
Hi,

I am using `/dist/tobii.min.js` in some of my projects and realized it is not working properly in IE11.

We can fix this by using `NodeList.prototype.forEach`-polyfill -> https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Polyfill

Can you confirm, @viliusle ?

**Comment by viliusle** [comment]
Do you know that github.com does not work on IE-11 ? ... Maybe it is time to let it go ...

**Comment by midzer** [comment]
We can drop it completely in an upcoming v3 https://github.com/midzer/tobii/issues/79
